# {0} - localized_path, {1} - themeName

# Sounds 
SoundManager.friend1_youChose="you chose"
SoundManager.friend1_youHaveMore="you have more!"
SoundManager.friend1_youHaveLess="you have less!"
SoundManager.friend1_andYouGet="you get"
SoundManager.friend1_landedOnTrap="you've landed on a trap!"

SoundManager.friend1_plus=
SoundManager.friend1_minus=
SoundManager.friend1_equals=
SoundManager.friend1_one=
SoundManager.friend1_two=
SoundManager.friend1_three=
SoundManager.friend1_four=
SoundManager.friend1_five=
SoundManager.friend1_six=
SoundManager.friend1_seven=
SoundManager.friend1_eight=
SoundManager.friend1_nine=
SoundManager.friend1_ten=
SoundManager.friend1_zero=
SoundManager.friend1_counting_one=
SoundManager.friend1_counting_two=
SoundManager.friend1_counting_three=
SoundManager.friend1_counting_four=
SoundManager.friend1_counting_five=
SoundManager.friend1_counting_six=
SoundManager.friend1_counting_seven=
SoundManager.friend1_counting_eight=
SoundManager.friend1_counting_nine=
SoundManager.friend1_counting_ten=

SoundManager.enemy1_wellSee="we'll see who gets the furtherest"
SoundManager.enemy1_andITake="I get"
SoundManager.enemy1_iTake="And I get"
SoundManager.enemy1_iWentTheFurtherest="i'm the one who went the furtherest"
SoundManager.enemy1_youWentTheFurtherest="you went the furtherest this time"
SoundManager.enemy1_moveMeForward="and now move me forward"
SoundManager.enemy1_youSentMeBack="oh no! you made me go back"
SoundManager.enemy1_youHaveToGoBack="ha ha you have to go back"
SoundManager.enemy1_iHaveTheMost="i've got the most"
SoundManager.enemy1_iHaveTheLeast="i have the least"
SoundManager.enemy1_landedOnTrap="Darn!  A trap!"
SoundManager.enemy1_iTookTheMost="Ha! I took the most"
SoundManager.enemy1_youreCatchingUp="Yikes!  You're catching up!"
SoundManager.enemy1_imStillAhead="I'm still ahead of you"
SoundManager.enemy1_imAhead="Ah ha... I'm ahead"
SoundManager.enemy1_tryToCatchMe="Try to catch me now"
SoundManager.enemy1_iveOvertakenYou="Ah ha!  I've overtaken you!"
SoundManager.enemy1_youveOvertakenMe="Uh oh!  You've overtaken me!"
SoundManager.enemy1_youreStillAhead="Oh no, you're still ahead of me"
SoundManager.enemy1_imCatchingUp="Ha ha!  I'm catching up!"
SoundManager.enemy1_justBehind="I'm just behind you"
SoundManager.enemy1_gettingBehind="I'm starting to get behind"
SoundManager.enemy1_imMilesBehind="Oh no, I'm miles behind..."

SoundManager.enemy1_plus=
SoundManager.enemy1_minus=
SoundManager.enemy1_equals=
SoundManager.enemy1_one=
SoundManager.enemy1_two=
SoundManager.enemy1_three=
SoundManager.enemy1_four=
SoundManager.enemy1_five=
SoundManager.enemy1_six=
SoundManager.enemy1_seven=
SoundManager.enemy1_eight=
SoundManager.enemy1_nine=
SoundManager.enemy1_ten=
SoundManager.enemy1_zero=
SoundManager.enemy1_counting_one=
SoundManager.enemy1_counting_two=
SoundManager.enemy1_counting_three=
SoundManager.enemy1_counting_four=
SoundManager.enemy1_counting_five=
SoundManager.enemy1_counting_six=
SoundManager.enemy1_counting_seven=
SoundManager.enemy1_counting_eight=

SoundManager.toContinue="click on the top right button to continue"
SoundManager.chooseSide="choose the side you want"
SoundManager.chooseQuickly="choose quickly!!"
SoundManager.watchOutNewTraps="Watch out! There are new traps"
SoundManager.moveYourCharacter="move your player forward"

SoundManager.chooseCharacter='choose your character'
SoundManager.characterLocked='this character is locked'
SoundManager.winToUnlock='you have to win more games to unlock it'
SoundManager.unlockedCharacter='Well done!  You've unlocked a new character!'

SoundManager.chooseTheme="Choose the world you want to play in"

SoundManager.gameOver="The game is over"
SoundManager.wellDone="Nice work, you won!"
SoundManager.badLuck="Bad luck, you lost this time"
SoundManager.youHaveWon="You have won"
SoundManager.gamesOutOf="games out of"
SoundManager.youGetReward="You are allowed to save a prisoner... click below to free him..."

SoundManager.takeReward="Save the prisoner by clicking on him..."
SoundManager.hereAreRewards="Here are all the animals you have saved! You need one of each type to unlock the next character"

SoundManager.instrucsUnderwater=sound for underWater/instructions.txt [INSTRUCTIONS] - key
SoundManager.instrucsJungle=sound for inJungle/instructions.txt [INSTRUCTIONS] - key

startMarker=Marks the start of the board
finishMarker=Marks the finish of the board
menuButton=Button to get to menu

# Texts
INSTRUCTIONS=Instructions for this theme
LICENSE_TEXT_PATH=localized LICENSE
CREDITS=Credits. Do not forget authors of the game !!!
CHAR_UNLOCK_CONDITION=Text explaining new character unlock condition
REG_SCREEN_INFO=Information you want to be presented inside HelpWindow in RegScreen
