<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fi.nmi.numberrace</groupId><artifactId>numberrace</artifactId><version>3.1.0</version><relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>numberrace-res</artifactId>
  <version>3.0.0</version>
  <name>NumberRace Resources</name>
  <build>
    <plugins>
      <plugin><artifactId>maven-resources-plugin</artifactId><version>3.3.1</version><configuration><encoding>UTF-8</encoding></configuration></plugin>
    </plugins>
  </build>
</project>
