# {0} - localized_path, {1} - themeName

# Sounds 
SoundManager.friend1_youChose=resources/{0}/sounds/Characters/Friend1/Dialog/tuaschoisi.wav
SoundManager.friend1_youHaveMore=resources/{0}/sounds/Characters/Friend1/Dialog/tuenplus.wav
SoundManager.friend1_youHaveLess=resources/{0}/sounds/Characters/Friend1/Dialog/tuenmoins.wav
SoundManager.friend1_andYouGet=resources/{0}/sounds/Characters/Friend1/Dialog/ettoituprends.wav
SoundManager.friend1_landedOnTrap=resources/{0}/sounds/Characters/Friend1/Dialog/tombesurpiege.wav

SoundManager.friend1_plus=resources/{0}/sounds/Characters/Friend1/Numbers/plus.wav
SoundManager.friend1_minus=resources/{0}/sounds/Characters/Friend1/Numbers/minus.wav
SoundManager.friend1_equals=resources/{0}/sounds/Characters/Friend1/Numbers/equals.wav

# Cumulative numbers
SoundManager.friend1_numbers_path=resources/{0}/sounds/Characters/Friend1/Numbers
SoundManager.friend1_numbers_counting_path=resources/{0}/sounds/Characters/Friend1/Numbers
SoundManager.enemy1_numbers_path=resources/{0}/sounds/Characters/Enemy1/Numbers
SoundManager.enemy1_numbers_counting_path=resources/{0}/sounds/Characters/Enemy1/Numbers

SoundManager.enemy1_wellSee=resources/{0}/sounds/Characters/Enemy1/Dialog/onvavoir.wav
SoundManager.enemy1_andITake=resources/{0}/sounds/Characters/Enemy1/Dialog/etmoijeprends.wav
SoundManager.enemy1_iTake=resources/{0}/sounds/Characters/Enemy1/Dialog/jeprends.wav
SoundManager.enemy1_iWentTheFurtherest=resources/{0}/sounds/Characters/Enemy1/Dialog/cestmoiquiaiavanceleplus.wav
SoundManager.enemy1_youWentTheFurtherest=resources/{0}/sounds/Characters/Enemy1/Dialog/tuesalleleplusloin.wav
SoundManager.enemy1_moveMeForward=resources/{0}/sounds/Characters/Enemy1/Dialog/etmaintenantfaismoiavancer.wav
SoundManager.enemy1_youSentMeBack=resources/{0}/sounds/Characters/Enemy1/Dialog/tumefaisreculer.wav
SoundManager.enemy1_youHaveToGoBack=resources/{0}/sounds/Characters/Enemy1/Dialog/hahatudoisreculer.wav
SoundManager.enemy1_iHaveTheMost=resources/{0}/sounds/Characters/Enemy1/Dialog/cestmoiquiaileplus.wav
SoundManager.enemy1_iHaveTheLeast=resources/{0}/sounds/Characters/Enemy1/Dialog/cestmoiquiailemoins.wav
SoundManager.enemy1_landedOnTrap=resources/{0}/sounds/Characters/Enemy1/Dialog/horreurpiege.wav
SoundManager.enemy1_iTookTheMost=resources/{0}/sounds/Characters/Enemy1/Dialog/hahajaipris.wav
SoundManager.enemy1_youreCatchingUp=resources/{0}/sounds/Characters/Enemy1/Dialog/ohlalatumerattrapes.wav
SoundManager.enemy1_imStillAhead=resources/{0}/sounds/Characters/Enemy1/Dialog/bonjesuistoujours.wav
SoundManager.enemy1_imAhead=resources/{0}/sounds/Characters/Enemy1/Dialog/jesuisentete.wav
SoundManager.enemy1_tryToCatchMe=resources/{0}/sounds/Characters/Enemy1/Dialog/essayerattraper.wav
SoundManager.enemy1_iveOvertakenYou=resources/{0}/sounds/Characters/Enemy1/Dialog/hahajeprendsavance.wav
SoundManager.enemy1_youveOvertakenMe=resources/{0}/sounds/Characters/Enemy1/Dialog/ohlatuprendsavance.wav
SoundManager.enemy1_youreStillAhead=resources/{0}/sounds/Characters/Enemy1/Dialog/zuttuestoujours.wav
SoundManager.enemy1_imCatchingUp=resources/{0}/sounds/Characters/Enemy1/Dialog/hahajeterattrape.wav
SoundManager.enemy1_justBehind=resources/{0}/sounds/Characters/Enemy1/Dialog/justederriere.wav
SoundManager.enemy1_gettingBehind=resources/{0}/sounds/Characters/Enemy1/Dialog/prendreretard.wav
SoundManager.enemy1_imMilesBehind=resources/{0}/sounds/Characters/Enemy1/Dialog/loinderriere.wav

SoundManager.enemy1_playerTooFar=resources/{0}/sounds/Characters/Enemy1/Dialog/p2far.wav
SoundManager.enemy1_opponentTooFar=resources/{0}/sounds/Characters/Enemy1/Dialog/o2far.wav

SoundManager.enemy1_plus=resources/{0}/sounds/Characters/Enemy1/Numbers/plus.wav
SoundManager.enemy1_minus=resources/{0}/sounds/Characters/Enemy1/Numbers/moins.wav
SoundManager.enemy1_equals=resources/{0}/sounds/Characters/Enemy1/Numbers/egale.wav

# SoundManager.toContinue=resources/{0}/sounds/Help/pourcontinuer.wav
SoundManager.chooseSide=resources/{0}/sounds/Help/choisiscote.wav
SoundManager.chooseQuickly=resources/{0}/sounds/Help/choisisvite.wav
SoundManager.watchOutNewTraps=resources/{0}/sounds/Help/attentionnouveauxpieges.wav
SoundManager.moveYourCharacter=resources/{0}/sounds/Help/faisavancerton.wav

SoundManager.chooseCharacter=resources/{0}/sounds/CharacChoiceScreen/choisispersonnage.wav
SoundManager.characterLocked=resources/{0}/sounds/CharacChoiceScreen/personnageverrouille.wav
SoundManager.winToUnlock=resources/{0}/sounds/CharacChoiceScreen/gagnerdeverrouiller.wav
SoundManager.unlockedCharacter=resources/{0}/sounds/CharacChoiceScreen/bravodeverrouille.wav

SoundManager.chooseTheme=resources/{0}/sounds/themeChoiceScreen/choisismonde.wav

SoundManager.gameOver=resources/{0}/sounds/GameOverScreen/lejeutermine.wav
SoundManager.wellDone=resources/{0}/sounds/GameOverScreen/bienjoue.wav
SoundManager.badLuck=resources/{0}/sounds/GameOverScreen/pasdechance.wav
SoundManager.youHaveWon=resources/{0}/sounds/GameOverScreen/tuasgagne.wav
SoundManager.gamesOutOf=resources/{0}/sounds/GameOverScreen/jeuxsur.wav
SoundManager.youGetReward=resources/{0}/sounds/GameOverScreen/authorisesauver.wav

SoundManager.takeReward=resources/{0}/sounds/RewardScreens/sauveprisonnier.wav
SoundManager.hereAreRewards=resources/{0}/sounds/RewardScreens/touslesanimaux.wav

SoundManager.instrucsUnderwater=resources/{0}/sounds/InstrucScreen/instrucsUnderwater.wav
SoundManager.instrucsJungle=resources/{0}/sounds/InstrucScreen/instrucsJungle.wav

SoundManager.introMusic=resources/sounds/music/intro.ogg
SoundManager.background2=resources/sounds/music/background2.ogg
SoundManager.background2LowVol=resources/sounds/music/background2LowVol.ogg
SoundManager.rewardMusic=resources/sounds/music/rewardMusic.ogg
SoundManager.rewardChoice=resources/sounds/music/rewardChoice.ogg

SoundManager.iconClick=resources/sounds/Effects/iconClick.ogg
SoundManager.chestOpen=resources/sounds/Effects/chestOpen.ogg
SoundManager.wrong2=resources/sounds/Effects/wrong2.ogg
SoundManager.wrong1=resources/sounds/Effects/wrong1.ogg
SoundManager.right=resources/sounds/Effects/right.ogg
SoundManager.cheer=resources/sounds/Effects/cheer.ogg

SoundManager.dolphinClick=resources/sounds/friend/noises/dolphinClick.ogg
SoundManager.dolphinSqueak=resources/sounds/friend/noises/dolphinSqueak.ogg
SoundManager.whale1Bubble=resources/sounds/friend/noises/whale1Bubble.ogg
SoundManager.whale2Bubble=resources/sounds/friend/noises/whale2Bubble.ogg
SoundManager.whale3Bubble=resources/sounds/friend/noises/whale3Bubble.ogg
SoundManager.orcaSplash=resources/sounds/friend/noises/orcaSplash.ogg

SoundManager.enemy1_crab2Click=resources/sounds/enemy/noises/crab2Click.ogg
SoundManager.crab3Click=resources/sounds/enemy/noises/crab3Click.ogg
SoundManager.puffFish=resources/sounds/enemy/noises/puffFish.ogg
SoundManager.squidSquirt=resources/sounds/enemy/noises/squidSquirt.ogg

SoundManager.anemone1=resources/sounds/hazards/anemone1.ogg
SoundManager.anemone2=resources/sounds/hazards/anemone2.ogg
SoundManager.anemone3=resources/sounds/hazards/anemone3.ogg

# Images
THEME_BACKGROUND_IMAGE=resources/images/{1}/background.gif
GAMEOVER_THEME_BACKGROUND_IMAGE=resources/images/{1}/gameover_background.gif
REWARD_BACKGROUND=resources/images/{1}/rewardScreen/rewardChoiceScreen.png
REWARDVIEW_BACKGROUND=resources/images/{1}/rewardScreen/rewardViewScreen.png
CHARACTER_CHOICE_BACKGROUND=resources/images/{1}/characChoicePage/characChoicePage.gif

hazard1a=resources/images/{1}/hazards/hazard1a.gif
hazard1b=resources/images/{1}/hazards/hazard1b.gif
hazard2a=resources/images/{1}/hazards/hazard2a.gif
hazard2b=resources/images/{1}/hazards/hazard2b.gif
hazard3a=resources/images/{1}/hazards/hazard3a.gif
hazard3b=resources/images/{1}/hazards/hazard3b.gif
cheatKey=resources/images/{1}/gameScreens/cheatKey.gif
reward1_left=resources/images/{1}/rewardScreen/reward1_left.gif
reward1_right=resources/images/{1}/rewardScreen/reward1_right.gif
reward2_left=resources/images/{1}/rewardScreen/reward2_left.gif
reward2_right=resources/images/{1}/rewardScreen/reward2_right.gif
reward3_left=resources/images/{1}/rewardScreen/reward3_left.gif
reward3_right=resources/images/{1}/rewardScreen/reward3_right.gif
reward4_left=resources/images/{1}/rewardScreen/reward4_left.gif
reward4_right=resources/images/{1}/rewardScreen/reward4_right.gif
reward5_left=resources/images/{1}/rewardScreen/reward5_left.gif
reward5_right=resources/images/{1}/rewardScreen/reward5_right.gif
reward6_left=resources/images/{1}/rewardScreen/reward6_left.gif
reward6_right=resources/images/{1}/rewardScreen/reward6_right.gif
reward7_left=resources/images/{1}/rewardScreen/reward7_left.gif
reward7_right=resources/images/{1}/rewardScreen/reward7_right.gif

startMarker=resources/images/{1}/startMarker.png
finishMarker=resources/images/{1}/finishMarker.png
menuButton=resources/images/{1}/menuButton.gif

helpButton=resources/images/{1}/gameScreens/helpButton.gif
choiceButton=resources/images/{1}/gameScreens/choiceButton.gif
boardButton=resources/images/{1}/gameScreens/boardButton.gif
scrSwitchButton=resources/images/{1}/gameScreens/scrSwitchButton.gif

leftContainerOpened=resources/images/{1}/gameScreens/leftContainerOpened.gif
leftContainerClosed=resources/images/{1}/gameScreens/leftContainerClosed.gif
rightContainerOpened=resources/images/{1}/gameScreens/rightContainerOpened.gif
rightContainerClosed=resources/images/{1}/gameScreens/rightContainerClosed.gif

# Character choice images
charac_1a=resources/images/{1}/characChoicePage/character_1a.gif
charac_1b=resources/images/{1}/characChoicePage/character_1b.gif
charac_2a=resources/images/{1}/characChoicePage/character_2a.gif
charac_2b=resources/images/{1}/characChoicePage/character_2b.gif
charac_3a=resources/images/{1}/characChoicePage/character_3a.gif
charac_3b=resources/images/{1}/characChoicePage/character_3b.gif
charac_4a=resources/images/{1}/characChoicePage/character_4a.gif
charac_4b=resources/images/{1}/characChoicePage/character_4b.gif
charac_5a=resources/images/{1}/characChoicePage/character_5a.gif
charac_5b=resources/images/{1}/characChoicePage/character_5b.gif
charac_6a=resources/images/{1}/characChoicePage/character_6a.gif
charac_6b=resources/images/{1}/characChoicePage/character_6b.gif

player_char_1a=resources/images/{1}/gameScreens/player_char_1a.gif
player_char_1b=resources/images/{1}/gameScreens/player_char_1b.gif
player_char_2a=resources/images/{1}/gameScreens/player_char_2a.gif
player_char_2b=resources/images/{1}/gameScreens/player_char_2b.gif
player_char_3a=resources/images/{1}/gameScreens/player_char_3a.gif
player_char_3b=resources/images/{1}/gameScreens/player_char_3b.gif
player_char_4a=resources/images/{1}/gameScreens/player_char_4a.gif
player_char_4b=resources/images/{1}/gameScreens/player_char_4b.gif
player_char_5a=resources/images/{1}/gameScreens/player_char_5a.gif
player_char_5b=resources/images/{1}/gameScreens/player_char_5b.gif
player_char_6a=resources/images/{1}/gameScreens/player_char_6a.gif
player_char_6b=resources/images/{1}/gameScreens/player_char_6b.gif

enemy_char_1a=resources/images/{1}/gameScreens/enemy_char_1a.gif
enemy_char_1b=resources/images/{1}/gameScreens/enemy_char_1b.gif
enemy_char_2a=resources/images/{1}/gameScreens/enemy_char_2a.gif
enemy_char_2b=resources/images/{1}/gameScreens/enemy_char_2b.gif
enemy_char_3a=resources/images/{1}/gameScreens/enemy_char_3a.gif
enemy_char_3b=resources/images/{1}/gameScreens/enemy_char_3b.gif
enemy_char_4a=resources/images/{1}/gameScreens/enemy_char_4a.gif
enemy_char_4b=resources/images/{1}/gameScreens/enemy_char_4b.gif

PAUSE_PNG=resources/images/pause.png

help_button=resources/images/help24x24.png
help_button.over=resources/images/helpOver24x24.png
help_button.pressed=resources/images/helpPressed24x24.png

# Texts
INSTRUCTIONS=resources/{0}/{1}/instructions.txt
LICENSE_TEXT_PATH=resources/{0}/LICENSE.txt
CREDITS=resources/{0}/credits.txt
CHAR_UNLOCK_CONDITION=resources/{0}/unlockCondition.txt
REG_SCREEN_INFO=resources/{0}/regScreenInfo.txt
