# Conceptual complexity dimension levels
# Format:
# NUM     1-40,         YES/NO,       YES/NO,          YES/NO,          max 9,          YES/NO,     NUM (in ms),         YES/NO,          YES/NO,            YES/NO,               Name
# Level = Board Length, Non-symbolic, Symbolic verbal, Symbolic arabic, Range ceilling, Dot fading, Dot fading duration, Hazards present, Addition required, Subtraction required, Starting Level
1 = 12,Yes,Yes,Yes,3,No,0,No,No,No,EASY
2 = 12,Yes,Yes,Yes,3,Yes,4000,No,No,No
3 = 12,Yes,Yes,Yes,3,Yes,1000,No,No,No
4 = 20,Yes,Yes,Yes,5,No,0,No,No,No
5 = 20,Yes,Yes,Yes,5,Yes,4000,No,No,No
6 = 20,Yes,Yes,Yes,5,Yes,1000,No,No,No
7 = 20,No,No,Yes,5,No,0,Yes,No,No
8 = 20,No,No,Yes,5,No,0,No,Yes,No,INTERMEDIATE
9 = 20,No,No,Yes,5,No,0,No,No,Yes
10 = 30,No,No,Yes,5,No,0,Yes,No,No
11 = 30,No,No,Yes,5,No,0,No,Yes,No
12 = 30,No,No,Yes,5,No,0,No,No,Yes
13 = 40,No,No,Yes,5,No,0,Yes,No,No
14 = 40,Yes,Yes,Yes,9,No,0,No,No,No,HARD
15 = 40,Yes,Yes,Yes,9,Yes,4000,No,No,No
16 = 40,Yes,Yes,Yes,9,Yes,1000,No,No,No
17 = 40,No,Yes,Yes,9,No,0,No,No,No
18 = 40,No,No,Yes,9,No,0,No,No,No
19 = 40,No,No,Yes,9,No,0,Yes,No,No
20 = 40,No,No,Yes,9,No,0,Yes,Yes,No
21 = 40,No,No,Yes,9,No,0,Yes,No,Yes
22 = 40,No,No,Yes,9,No,0,Yes,Yes,Yes
